server:
  port: 8080
spring:
  key:
    file:
      path: src/main/resources/AES_KEY.key
  image:
    max:
      width: 5000
      height: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/image-app?&serverTimezone=UTC&ssl-mode=REQUIRED
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      open-in-view: false
